// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnT5ulJ-U6O07SBcmNxxjcIYRlVVh0qhE',
    appId: '1:161636546935:web:66e85bc9342ee4caf14972',
    messagingSenderId: '161636546935',
    projectId: 'salescloudapp',
    authDomain: 'salescloudapp.firebaseapp.com',
    storageBucket: 'salescloudapp.firebasestorage.app',
    measurementId: 'G-SER6ZQXRKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0LEwRrazdwA1ase8B5h7cDMU4CXWJcrI',
    appId: '1:161636546935:android:167b476cf0e3076cf14972',
    messagingSenderId: '161636546935',
    projectId: 'salescloudapp',
    storageBucket: 'salescloudapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_e7ahoPlChu-bu2riSUhCTEXEnPyBcwI',
    appId: '1:161636546935:ios:043875561b1f44b8f14972',
    messagingSenderId: '161636546935',
    projectId: 'salescloudapp',
    storageBucket: 'salescloudapp.firebasestorage.app',
    iosBundleId: 'com.example.invoiceApp',
  );
}
