// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEiap9fiqjJBkpD6wAmNancWN0yMv9cfE',
    appId: '1:1030264475163:web:ce12433ed54f20af9732be',
    messagingSenderId: '1030264475163',
    projectId: 'astana-distribution',
    authDomain: 'astana-distribution.firebaseapp.com',
    storageBucket: 'astana-distribution.firebasestorage.app',
    measurementId: 'G-98W4NQ9NJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaP4Z88SqLPozYqTBx0iIS4mEmLMtCE5A',
    appId: '1:1030264475163:android:bad9bf16420679b09732be',
    messagingSenderId: '1030264475163',
    projectId: 'astana-distribution',
    storageBucket: 'astana-distribution.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEvOBUc96DZecHG9W2i3DqTW-8JWO0uuE',
    appId: '1:1030264475163:ios:6355ef969d568d619732be',
    messagingSenderId: '1030264475163',
    projectId: 'astana-distribution',
    storageBucket: 'astana-distribution.firebasestorage.app',
    iosBundleId: 'com.example.invoiceApp',
  );

}